CREATE DATABASE Marketa
GO

USE Marketa
GO

CREATE TABLE tblTipoUsuario(
IdTipoUsuario INT NOT NULL PRIMARY KEY IDENTITY,
TipoUsuario VARCHAR(20) NOT NULL,
)

CREATE TABLE tblUsuario(
IdUsuario INT NOT NULL PRIMARY KEY IDENTITY,
IdTipoUsuario INT NOT NULL REFERENCES tblTipoUsuario(IdTipoUsuario),
Cedula CHAR(11) NOT NULL UNIQUE,
Nombre VARCHAR(20) NOT NULL,
Apellidos VARCHAR(20) NOT NULL,
Contraseña VARCHAR(50) NOT NULL,
Telefono CHAR(10) NOT NULL,
Direccion VARCHAR(50) NOT NULL,
Activo BIT
)

CREATE TABLE tblCliente (
IdCliente INT NOT NULL PRIMARY KEY IDENTITY,
Nombre VARCHAR(20) NOT NULL,
Apellido VARCHAR(20) NOT NULL,
Telefono CHAR(10) NOT NULL,
Direccion VARCHAR(50) NOT NULL,
MontoDebe DECIMAL(10,2),
FechaRegistro DATETIME
)

CREATE TABLE tblCategoriaP (
IdCategoriaP INT NOT NULL PRIMARY KEY IDENTITY,
Nombre VARCHAR(20) NOT NULL,
Descripcion VARCHAR(50) NOT NULL
)

CREATE TABLE tblProducto(
IdProducto INT NOT NULL PRIMARY KEY IDENTITY,
IdCategoriaP INT NOT NULL REFERENCES tblCategoriaP(IdCategoriaP),
NombreProducto VARCHAR(50) NOT NULL,
Precio DECIMAL(10,2) NOT NULL,
NumExistencias DECIMAL(10,2) NOT NULL,
Descuento DECIMAL(10,2) NOT NULL,
AplicaITBIS BIT NOT NULL
)

CREATE TABLE tblPagoDeuda(
IdPagoDeuda INT NOT NULL PRIMARY KEY IDENTITY,
IdUsuario INT REFERENCES tblUsuario(IdUsuario),
IdCliente INT NOT NULL REFERENCES tblCliente(IdCliente),
Fecha DATETIME NOT NULL,
DeudaAnterior DECIMAL(10,2) NOT NULL,
Bono DECIMAL(10,2) NOT NULL
)

CREATE TABLE tblFactura(
IdFactura INT NOT NULL PRIMARY KEY IDENTITY,
IdCliente INT NOT NULL REFERENCES tblCliente(IdCliente),
IdUsuario INT NOT NULL REFERENCES tblUsuario(IdUsuario),
TotalITBIS DECIMAL(10,2) NOT NULL,
TotalDescuento DECIMAL(10,2) NOT NULL,
TotalGeneral DECIMAL(10,2) NOT NULL,
Pago DECIMAL(10,2) NOT NULL,
)

CREATE TABLE tblFacturaD(
IdDetalle INT NOT NULL PRIMARY KEY IDENTITY,
IdFactura INT NOT NULL REFERENCES tblFactura(IdFactura),
IdProducto INT NOT NULL REFERENCES tblProducto(IdProducto),
Precio DECIMAL(10,2) NOT NULL,
ITBIS DECIMAL(10,2) NOT NULL,
Cantidad INT NOT NULL,
Descuento DECIMAL(10,2) NOT NULL,
)
